/** i18n keys required by the Understanding (tensions) page — Step 036. */
export const UNDERSTANDING_PAGE_I18N_KEYS = [
  "nav.understanding",
  "understanding.title",
  "understanding.subtitle",
  "understanding.banner",
  "understanding.empty_title",
  "understanding.empty",
  "understanding.loading",
  "understanding.error_load",
  "understanding.col.type",
  "understanding.col.summary",
  "understanding.col.claims",
  "understanding.col.observations",
  "understanding.col.evidence",
  "understanding.type.support_deficit",
  "understanding.type.conflict",
  "understanding.filter.all",
  "understanding.filter.support_deficit",
  "understanding.filter.conflict",
  "understanding.metric.total",
  "understanding.metric.total_help",
  "understanding.metric.support_deficit",
  "understanding.metric.conflict",
  "understanding.metric.page",
  "understanding.metric.page_help",
  "understanding.expand",
  "understanding.collapse",
  "understanding.detail.summary",
  "understanding.detail.json",
  "understanding.copy_json",
  "understanding.copy_ok",
  "understanding.copy_fail",
] as const;
