"""Lexical (keyword) retrieval over chunks using PostgreSQL full-text search.

Chunks carry a generated ``search_vector`` (``tsvector``) column maintained by
PostgreSQL itself (see :mod:`app.core.db_extras`), so there is no separate index
to keep in sync — inserting/deleting a chunk row updates its vector
automatically. Search uses ``to_tsquery`` + ``ts_rank`` over a GIN index.

The ``simple`` text-search configuration is used (no language-specific stemming
or stopwords) which suits Ukrainian and mixed-language content.
"""
from __future__ import annotations

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.core.database import engine
from app.core.logging import get_logger
from app.services.content_signals import tokenize

logger = get_logger(__name__)

# Light morphological variants for FTS ``simple`` (no language stemmer).
# Longest suffixes first. Domain-agnostic — helps any inflected language site.
_LEXICAL_SUFFIXES: tuple[str, ...] = (
    "ями",
    "ами",
    "ові",
    "еві",
    "ах",
    "ях",
    "ом",
    "ем",
    "ів",
    "ев",
    "ов",
    "ам",
    "ям",
    "ою",
    "ею",
    "ию",
    "ий",
    "ій",
    "ый",
    "ая",
    "ое",
    "ие",
    "іе",
    "ing",
    "ers",
    "ies",
    "es",
    "ed",
    "s",
    "и",
    "і",
    "ы",
    "у",
    "ю",
    "а",
    "я",
    "е",
    "о",
)

_LEXICAL_STOPWORDS = frozenset(
    {
        "the",
        "and",
        "for",
        "with",
        "from",
        "that",
        "this",
        "what",
        "which",
        "how",
        "are",
        "was",
        "were",
        "по",
        "на",
        "у",
        "в",
        "і",
        "та",
        "або",
        "для",
        "про",
        "як",
        "які",
        "який",
        "яка",
        "що",
        "це",
        "чи",
        "з",
        "із",
        "до",
        "від",
        "за",
    }
)


def lexical_term_variants(term: str) -> list[str]:
    """Return base token plus one light morphological reduction when safe."""
    tok = (term or "").strip().lower()
    if len(tok) < 4 or tok in _LEXICAL_STOPWORDS:
        return [tok] if tok and tok not in _LEXICAL_STOPWORDS else []
    out = [tok]
    for suf in _LEXICAL_SUFFIXES:
        if tok.endswith(suf) and len(tok) - len(suf) >= 4:
            stem = tok[: -len(suf)]
            if stem and stem not in out:
                out.append(stem)
            break
    return out


class LexicalIndexService:
    def __init__(self, db: Session) -> None:
        self.db = db

    @property
    def enabled(self) -> bool:
        return engine.dialect.name == "postgresql"

    # The search_vector column is generated by PostgreSQL, so per-chunk index
    # maintenance is a no-op. These methods are kept for call-site compatibility.
    def index_chunk(
        self,
        *,
        chunk_id: int,
        source_id: int,
        text_value: str,
        title: str,
        heading: str,
        url: str,
    ) -> None:
        return None

    def delete_for_source(self, source_id: int) -> None:
        return None

    def delete_all(self) -> None:
        return None

    @staticmethod
    def build_match_query(terms: list[str], phrase: str = "") -> str:
        """Build a safe ``to_tsquery`` expression from terms (+ optional phrase).

        Each lexeme is single-quoted (and internal quotes escaped) so that user
        input cannot inject tsquery operators. Tokens are OR-ed (``|``) for
        recall; the full phrase is added as an adjacency group (``<->``) to
        reward exact ordering. Inflected tokens also contribute a light stem
        variant so ``депозитах`` can match ``депозит`` under ``simple`` FTS.
        """
        parts: list[str] = []
        seen: set[str] = set()
        for term in terms:
            for tok in tokenize(term):
                for variant in lexical_term_variants(tok):
                    if variant in seen:
                        continue
                    seen.add(variant)
                    parts.append("'" + variant.replace("'", "''") + "'")
        expr = " | ".join(parts)

        phrase_tokens = [
            t for t in tokenize(phrase) if t not in _LEXICAL_STOPWORDS
        ]
        if len(phrase_tokens) > 1:
            adj = " <-> ".join("'" + t.replace("'", "''") + "'" for t in phrase_tokens)
            expr = f"({expr}) | ({adj})" if expr else f"({adj})"
        return expr

    def search(
        self,
        match_query: str,
        top_k: int,
        *,
        exclude_document_types: list[str] | tuple[str, ...] | None = None,
    ) -> list[tuple[int, int, float]]:
        """Return [(chunk_id, source_id, rank)] best-first (higher rank=better).

        When ``exclude_document_types`` is set, join ``sources`` and skip those
        structural types. Used to refill candidate pools when news/promo FTS
        flood would otherwise starve preferred evidence families.
        """
        if not self.enabled or not match_query.strip():
            return []
        excluded = [
            str(t).strip()
            for t in (exclude_document_types or ())
            if str(t).strip()
        ]
        try:
            if excluded:
                rows = self.db.execute(
                    text(
                        "SELECT c.id, c.source_id, "
                        "ts_rank(c.search_vector, q) AS rank "
                        "FROM chunks c "
                        "JOIN sources s ON s.id = c.source_id "
                        ", to_tsquery('simple', :q) AS q "
                        "WHERE c.search_vector @@ q "
                        "AND s.status = 'indexed' "
                        "AND s.document_type <> ALL(:excluded) "
                        "ORDER BY rank DESC LIMIT :k"
                    ),
                    {"q": match_query, "k": top_k, "excluded": excluded},
                ).all()
            else:
                rows = self.db.execute(
                    text(
                        "SELECT c.id, c.source_id, "
                        "ts_rank(c.search_vector, q) AS rank "
                        "FROM chunks c, to_tsquery('simple', :q) AS q "
                        "WHERE c.search_vector @@ q "
                        "ORDER BY rank DESC LIMIT :k"
                    ),
                    {"q": match_query, "k": top_k},
                ).all()
        except Exception as exc:  # noqa: BLE001
            logger.warning("Lexical search failed: %s", exc)
            return []
        return [(int(r[0]), int(r[1]), float(r[2])) for r in rows]
