"""Initial PostgreSQL schema.

Creates the full application schema from the ORM models (the canonical current
schema) plus the PostgreSQL full-text ``search_vector`` column and GIN index on
``chunks``. Subsequent changes should be expressed as autogenerated migrations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-30

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

from app import models  # noqa: F401  (register models on Base.metadata)
from app.core.database import Base
from app.core.db_extras import apply_fulltext_extras, drop_fulltext_extras

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)
    apply_fulltext_extras(bind)


def downgrade() -> None:
    bind = op.get_bind()
    drop_fulltext_extras(bind)
    Base.metadata.drop_all(bind=bind)
